theme_color:
  primary: brown
  accent: blue

notice: ã€ğŸ’–æ¬¢è¿æ¥åˆ°æœ¬ç«™ï¼Œå¦‚æœå–œæ¬¢å°±ç•™ä¸ªè¨€å§ğŸ’–ã€‘

favicon: /images/favicon/favicon.jpg
banner: /images/banner/banner.jpg
avatar: /images/avatar/avatar.jpg
rss: /atom.xml

email: 380372667@qq.com
sns:
  #twitter:
  #facebook:
  #google_plus:
  weibo: https://weibo.com/3030289530/profile
  #instagram:
  #tumblr:
  github: https://github.com/duanxiguan
  #linkedin:
  zhihu: https://www.zhihu.com/people/duanxiguan
  #3douban:
  qq: tencent://message/?uin=380372667&Menu=yes
  wechat:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google: fXjtlIfaDc_X-0P11rO3bEp1Nk4IKXphoJv0GqGZCco
  baidu: I3t1wfwZvd
analytics:
  google_site_id: UA-139531378-1
  baidu_site_id: 22e4d3b73c21ec2f0e1b4f3ff78c9a9c
  cnzz_site_id:

pages:
  - name: æ—¶é—´è½´
    link: /timeline
  - name: æ ‡ç­¾äº‘
    link: /tagcloud
  - name: ç›¸å†Œ
    link: /gallery
  - name: ç”µè§†ç›´æ’­
    link: /tv
  - name: å›¾çµå½•æ’­
    link: /tllb
  - name: å›¾çµéŸ³ä¹
    link: /tlyy
  - name: æˆ‘çš„è§†é¢‘
    link: /wdsp
  - name: æˆ‘çš„éŸ³ä¹
    link: /wdyy
links:
  - name: è‡ªå»ºæœåŠ¡å¯¼èˆª
    link: //home.niemingzhao.top

since: 2016
footer_text: ' | Theme - <a href="https://github.com/niemingzhao/niemingzhao.github.io/tree/theme" target="_blank" class="mdui-text-color-theme-accent">default</a><br>äº¬å…¬ç½‘å®‰å¤‡<a href="https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502053272" target="_blank" class="mdui-text-color-theme-accent">11010502053272</a>å· | äº¬ICPå¤‡<a href="https://beian.miit.gov.cn" target="_blank" class="mdui-text-color-theme-accent">2023020255</a>å·'
license: æœ¬æ–‡éµå¾ª <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a> è®¸å¯åè®®

gallery:
  fancybox_css: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: //cdn.bootcdn.net/ajax/libs/jquery/3.3.1/jquery.min.js
  lazyload_js: //cdn.bootcdn.net/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: å‘é€åˆ°æ‰‹æœº
  use: plugin
donate:
  - name: æ”¯ä»˜å®
    link: /images/alipay/alipay.jpg
  - name: å¾®ä¿¡æ”¯ä»˜
    link: /images/wechatpay/wechatpay.jpg
search:
  placeholder: è¯·è¾“å…¥å…³é”®å­—
  path: /search.xml
  use: plugin
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id: Ov23liCETeAlI7NPJZhc 
  gitalk_client_secret: 48a5731e14b3b42e32ad0a53f042ea71ca432517
  gitalk_repo: duanxiguan.github.io
  gitalk_owner: duanxiguan
  gitalk_sid_type: uuid
  livere_data_uid:  
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
